export const ALL_SUGGESTION_CHIPS = [
  { emoji: '💰', label: 'Budget PG under ₹5000' },
  { emoji: '🏋️', label: 'PG with Gym & Pool' },
  { emoji: '🍕', label: 'PG with Meals Included' },
  { emoji: '📶', label: 'PG with WiFi & AC' },
  { emoji: '👫', label: 'Couples Friendly PG' },
  { emoji: '🚇', label: 'PG near Metro Station' },
  { emoji: '🔒', label: 'Secure PG with CCTV' },
  { emoji: '🛋️', label: 'Fully Furnished PG' },
  { emoji: '🧼', label: 'PG with Laundry Service' },
  { emoji: '🎓', label: 'Student Friendly PG' },
  { emoji: '💼', label: 'Working Professionals PG' },
  { emoji: '🚗', label: 'PG with Car Parking' },
  { emoji: '🧹', label: 'Daily Housekeeping' },
  { emoji: '📺', label: 'PG with Smart TV' },
  { emoji: '🎮', label: 'Coliving with Gaming Room' },
  { emoji: '🍳', label: 'Self Cooking Kitchen' },
  { emoji: '🌳', label: 'PG with Balcony & Park' },
  { emoji: '🚶', label: 'Walking Distance to IT Park' },
  { emoji: '🐾', label: 'Pet Friendly PG' },
  { emoji: '🛏️', label: 'Single Occupancy Room' },
  { emoji: '👯', label: 'Double Sharing Room' },
  { emoji: '🧊', label: 'PG with Refrigerator' },
  { emoji: '☀️', label: 'PG with Natural Light' },
  { emoji: '🌙', label: 'No Late Night Curfew' },
  { emoji: '🏢', label: 'Luxury Coliving Spaces' },
  { emoji: '🔐', label: 'Biometric Access PG' },
  { emoji: '🔥', label: 'PG with Water Heater' },
  { emoji: '🔋', label: '24/7 Power Backup' },
  { emoji: '🚰', label: 'RO Water Purifier' },
  { emoji: '🛌', label: 'Cozy PG with Spring Mattress' },
  { emoji: '🚌', label: 'PG near Bus Stand' },
  { emoji: '🛍️', label: 'PG near Shopping Mall' },
  { emoji: '🏥', label: 'PG near Hospital/Clinic' },
  { emoji: '🍽️', label: 'PG with Dining Area' },
  { emoji: '📖', label: 'Quiet Study Room included' }
];

export const PLACEHOLDER_EXAMPLES = [
  'Where do you want to live? (e.g. city, neighborhood, or landmark)',
  'Try searching near your college or university...',
  'Enter a neighborhood, street, or tech park...',
  'Search near your workplace or office...',
  'Type any popular landmark nearby...',
  'Where are you moving next? Enter a locality...',
  'Search by city name to see all options...',
  'Find PGs near the closest metro station...',
  'Look for accommodations near the city center...',
  'Enter any street name or area to explore PGs...'
];

export const TEXTAREA_PLACEHOLDERS = [
  'Any specific requirements? (e.g. Cheap unisex PG under 5000)',
  'What else do you need? (e.g. WiFi, AC, Gym, Meals)',
  'Tell us more... (e.g. Single room with attached bathroom)',
  'Looking for something special? (e.g. Pet friendly, no curfew)',
  'Add details... (e.g. Walking distance to metro station)',
  'Any preferences? (e.g. Double sharing with balcony)',
  'Must-haves? (e.g. 24/7 power backup, RO water, geyser)',
  'Food preferences? (e.g. Veg only meals included)',
  'Transport needs? (e.g. Needs car parking or near bus stop)',
  'Security requirements? (e.g. Biometric entry, CCTV cameras)',
  'Work from home setup? (e.g. High speed internet, study table)',
  'Budget constraints? (e.g. Strictly under ₹8000 per month)'
];
